run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - bin
    - vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  # sorts results by: filepath, line and column
  sort-results: true
