services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: ${PWD}/db/data.sqlite
        target: /app/database.db
  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
