version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: ${PWD}/db/data.sqlite
        target: /app/db/data.sqlite
      - type: bind
        source: ${PWD}/configs/prod.json
        target: /app/configs/prod.json
      - type: bind
        source: ${PWD}/website/src
        target: /app/website/src
    ports:
      - "7000:7000"

  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
