openapi: 3.0.2
servers: 
  - url: /v1
info: 
  version: 1.0.0
  title: multichat bot api
tags: 
  - name: twitch
    description: Twitch service api
  - name: youtube
    description: youtube service api
paths: 
  '/twitch/{chat}':
    post:
      tags:
        - twitch
      summary: Join the twitch chat for the specified channel
      description: ''
      operationId: joinTwitchChat
      responses:
        '200':
          description: Successful operation
        '500':
          description: Unable to join chat
      parameters:
        - name: chat
          in: path
          description: the username to connect to the chat
          required: true
          schema:
            type: string
    delete:
      tags:
        - twitch
      summary: Leave the twitch chat for the specified channel
      description: ''
      operationId: leaveTwitchChat
      responses:
        '200':
          description: Successful operation
        '500':
          description: Unable to leave chat
      parameters:
        - name: chat
          in: path
          description: the username to leave to the chat
          required: true
          schema:
            type: string